"use client";
import { Dumbbell, Share2, Trash2 } from "lucide-react";
import { useState } from "react";
import { PageHeader } from "@/components/page-header";
import { useRepMate } from "@/components/providers/app-provider";
import { ShareRecap } from "@/components/share-recap";
import type { Workout } from "@/lib/types";
import { workoutStats } from "@/lib/workouts";

export default function ProgressPage(){const state=useRepMate();const [sharing,setSharing]=useState<Workout|null>(null);const [now]=useState(()=>Date.now());const completed=state.workouts.filter(w=>w.completedAt).sort((a,b)=>Date.parse(b.completedAt!)-Date.parse(a.completedAt!));const totals=completed.reduce((a,w)=>{const s=workoutStats(w);return{sets:a.sets+s.sets,volume:a.volume+s.volume}}, {sets:0,volume:0});return <div className="app-page"><PageHeader eyebrow="Strength over time" title="Progress"/><section className="grid grid-cols-2 gap-3">{[[completed.length,"Workouts"],[completed.filter(w=>now-Date.parse(w.completedAt!)<604800000).length,"This week"],[totals.sets,"Total sets"],[`${Math.round(totals.volume).toLocaleString()} ${state.profile.units}`,"Total volume"]].map(([v,l])=><div key={l} className="flex min-h-28 flex-col justify-between rounded-2xl border border-white/10 bg-[#111] p-4"><strong className="numeric text-xl">{v}</strong><span className="text-sm text-zinc-500">{l}</span></div>)}</section><section className="rounded-3xl border border-white/10 bg-[#111] p-5"><h2 className="display text-2xl">Training volume</h2><p className="text-sm text-zinc-500">Completed session volume</p>{completed.length<2?<div className="grid min-h-52 place-items-center text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-2xl border border-white/10"><Dumbbell className="size-5"/></span><p className="mt-4 max-w-56 text-sm text-zinc-500">Complete two workouts to see your training trend.</p></div></div>:<div className="mt-8 flex h-48 items-end gap-3">{completed.slice(0,8).reverse().map(w=>{const value=workoutStats(w).volume,max=Math.max(...completed.map(x=>workoutStats(x).volume));return <div key={w.id} className="flex h-full flex-1 items-end"><div className="w-full rounded-t-lg bg-white/80" style={{height:`${Math.max(8,value/max*100)}%`}} title={`${value} ${state.profile.units}`}/></div>})}</div>}</section><h2 className="text-lg font-semibold">Workout history</h2>{completed.map(w=>{const stats=workoutStats(w);return <article key={w.id} className="rounded-2xl border border-white/10 bg-[#111] p-4"><div className="flex items-start justify-between"><div><h3 className="font-semibold">{w.name}</h3><p className="mt-1 text-xs text-zinc-500">{new Date(w.completedAt!).toLocaleString()} · {stats.sets} sets · {Math.round(stats.volume)} {state.profile.units}</p></div><div className="flex gap-2"><button onClick={()=>setSharing(w)} className="grid size-10 place-items-center rounded-xl border border-white/10" aria-label="Share recap"><Share2 className="size-4"/></button><button onClick={()=>confirm("Delete this workout?")&&state.removeWorkout(w.id)} className="grid size-10 place-items-center rounded-xl border border-red-500/20 text-red-400" aria-label="Delete workout"><Trash2 className="size-4"/></button></div></div></article>})}{sharing&&<ShareRecap workout={sharing} profile={state.profile} onClose={()=>setSharing(null)}/>}</div>}
