"use client";
import { useState } from "react";
import { Copy, Pencil, Play, Plus, Trash2 } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { useRepMate } from "@/components/providers/app-provider";
import { RoutineEditor } from "@/components/routine-editor";
import { Button } from "@/components/ui/button";
import type { Program, Routine } from "@/lib/types";
import { weekdays } from "@/lib/data";
import { createWorkout } from "@/lib/workouts";
import { useRouter } from "next/navigation";

export default function ProgramsPage(){const state=useRepMate(),router=useRouter();const [editing,setEditing]=useState<{program:Program;routine:Routine}|null>(null);
const create=async()=>{const id=crypto.randomUUID();await state.saveProgram({id,name:"My Program",split:"Custom",active:!state.programs.length,days:[]})};
const addRoutine=async(program:Program)=>{const routine={id:crypto.randomUUID(),name:`Workout ${program.days.length+1}`,weekday:1,muscles:[],exercises:[]};await state.saveProgram({...program,days:[...program.days,routine]});setEditing({program:{...program,days:[...program.days,routine]},routine})};
const start=async(program:Program,routine:Routine)=>{await state.setActive(createWorkout(program,routine));router.push("/app/workout")};
return <div className="app-page"><PageHeader eyebrow="Plan your training" title="Program" action={<Button onClick={create} variant="secondary"><Plus className="size-4"/>New</Button>}/><div className="program-list">{state.programs.map(program=><section key={program.id} className="program-card-native"><header className="program-card-native__head"><div><p className="eyebrow">{program.split}</p><h2>{program.name}</h2></div><span className="program-status">{program.active?"Active":"Inactive"}</span></header><div className="program-days">{program.days.map((routine,index)=><article key={routine.id} className="program-day-native"><span className="program-day-native__number numeric">{String(index+1).padStart(2,"0")}</span><div className="program-day-native__copy"><h3>{routine.name}</h3><p>{routine.exercises.length} exercises · {weekdays[routine.weekday]} · {routine.muscles.join(", ")}</p></div><div className="program-day-native__actions"><button onClick={()=>setEditing({program,routine})} className="program-icon-action" aria-label={`Edit ${routine.name}`}><Pencil/></button><button disabled={!routine.exercises.length} onClick={()=>start(program,routine)} className="program-icon-action program-icon-action--start" aria-label={`Start ${routine.name}`}><Play/></button></div></article>)}<button onClick={()=>addRoutine(program)} className="program-add-routine"><Plus/>Add routine</button></div><footer className="program-card-native__footer"><Button variant="secondary" onClick={()=>state.saveProgram({...program,id:crypto.randomUUID(),name:`${program.name} Copy`,active:false})}><Copy className="size-4"/>Copy plan</Button>{!program.active&&<Button variant="secondary" onClick={()=>Promise.all(state.programs.map(p=>state.saveProgram({...p,active:p.id===program.id})))}>Activate</Button>}<Button variant="danger" onClick={()=>state.removeProgram(program.id)}><Trash2 className="size-4"/>Delete</Button></footer></section>)}</div>{editing&&<RoutineEditor key={editing.routine.id} program={editing.program} routine={editing.routine} open onOpenChange={open=>!open&&setEditing(null)} onSave={state.saveProgram}/>}</div>}
